version: '3.7'

services:

  mysql:
    image: mariadb:5.5
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: verySecret

  hashtopolis:
    image: kpeiruza/hashtopolis:latest
#    image: htp:latest  # use this if you built your own image using 'docker build <PATH_TO_DOCKERFILE> -t htp:latest
    depends_on:
      - mysql
    environment:
      H8_USER: root
      H8_PASS: verySecret
      H8_EMAIL: root@localhost
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: verySecret
      MYSQL_DB: hashtopolis
      HTP_SERVER_NAME: htp.example.com
      HTP_MEMORY_LIMIT: 512M
      HTP_UPLOAD_MAX_SIZE: 500M
    volumes:
      - import:/var/www/html/import
      - files:/var/www/html/files
      - inc:/var/www/html/inc
      - locks:/var/www/html/inc/utils/locks
    ports:
      - "8000:80"

volumes:
  import: {}
  files: {}
  inc: {}
  locks: {}
  mysql: {}
